export const mockCards = [
  { "id": 1, "subject": "Mathematics", "type": "Essay", "words": 500, "content": "An introduction to calculus and its applications in modern science and engineering, covering fundamental concepts like derivatives and integrals." },
  { "id": 2, "subject": "Science", "type": "Report", "words": 1800, "content": "A comprehensive study on the impact of climate change on marine ecosystems, focusing on coral bleaching and shifting biodiversity patterns." },
  { "id": 3, "subject": "History", "type": "Article", "words": 6000, "content": "The fall of the Roman Empire and its long-term effects on European politics, culture, and social structures throughout the Middle Ages." },
  { "id": 4, "subject": "English", "type": "Essay", "words": 700, "content": "A detailed literary analysis of Shakespeare's Hamlet, exploring themes of madness, revenge, and moral ambiguity in the famous tragedy." },
  { "id": 5, "subject": "Science", "type": "Report", "words": 800, "content": "The crucial role of photosynthesis in sustaining life on Earth, converting sunlight into chemical energy for plants and animals." },
  { "id": 6, "subject": "Mathematics", "type": "Report", "words": 1200, "content": "Understanding probability theory and its practical applications in real-world scenarios like weather forecasting and financial markets." },
  { "id": 7, "subject": "English", "type": "Essay", "words": 900, "content": "Exploring modern poetry movements and their significant influence on contemporary literature and cultural expression worldwide." },
  { "id": 8, "subject": "History", "type": "Article", "words": 7500, "content": "A thorough examination of the Industrial Revolution and its profound societal impact on urbanization and working conditions." },
  { "id": 9, "subject": "Science", "type": "Report", "words": 1500, "content": "The complex structure and function of the human brain, including recent discoveries in neuroscience and cognitive research." },
  { "id": 10, "subject": "Mathematics", "type": "Essay", "words": 600, "content": "An exploration of fractals and their fascinating occurrence in natural phenomena like coastlines and snowflakes." },
  { "id": 11, "subject": "English", "type": "Essay", "words": 1100, "content": "The historical evolution of the English language over centuries, from Old English to modern global communication." },
  { "id": 12, "subject": "Science", "type": "Report", "words": 2000, "content": "Current advancements in space exploration and the ongoing scientific search for extraterrestrial life in our universe." },
  { "id": 13, "subject": "History", "type": "Article", "words": 5000, "content": "World War II: Analyzing the root causes, major events, and lasting global consequences of this devastating conflict." },
  { "id": 14, "subject": "Mathematics", "type": "Essay", "words": 1300, "content": "The Pythagorean Theorem explained with practical examples of its applications in geometry and architectural design." },
  { "id": 15, "subject": "Science", "type": "Report", "words": 900, "content": "Understanding genetic inheritance patterns and modern DNA sequencing techniques revolutionizing medical research." },
  { "id": 16, "subject": "History", "type": "Article", "words": 4500, "content": "The Renaissance period and its groundbreaking contributions to art, science, and humanistic philosophy across Europe." },
  { "id": 17, "subject": "English", "type": "Essay", "words": 950, "content": "The cultural importance of storytelling throughout human history as a means of preserving knowledge and values." },
  { "id": 18, "subject": "Science", "type": "Report", "words": 2100, "content": "The rapid development and promising future of renewable energy sources to combat climate change effectively." },
  { "id": 19, "subject": "Mathematics", "type": "Essay", "words": 1400, "content": "Exploring the mind-bending concept of infinity in mathematics and its paradoxical implications in set theory." },
  { "id": 20, "subject": "History", "type": "Article", "words": 7000, "content": "The American Civil War analyzed through multiple perspectives and its lasting impact on modern democratic systems." },
  { "id": 21, "subject": "Mathematics", "type": "Report", "words": 850, "content": "Linear algebra fundamentals and their essential applications in computer graphics and machine learning algorithms." },
  { "id": 22, "subject": "Science", "type": "Essay", "words": 1200, "content": "The fascinating world of quantum mechanics and its counterintuitive principles that challenge classical physics." },
  { "id": 23, "subject": "History", "type": "Article", "words": 5500, "content": "Ancient Egyptian civilization: Exploring its remarkable achievements in architecture, medicine, and early writing systems." },
  { "id": 24, "subject": "English", "type": "Essay", "words": 750, "content": "Comparative analysis of dystopian literature in 20th century novels and contemporary political realities." },
  { "id": 25, "subject": "Science", "type": "Report", "words": 1900, "content": "Plate tectonics theory and its explanation of earthquakes, volcanoes, and continental drift patterns worldwide." },
  { "id": 26, "subject": "Mathematics", "type": "Essay", "words": 1100, "content": "Game theory applications in economics, political science, and everyday decision-making processes and strategies." },
  { "id": 27, "subject": "English", "type": "Report", "words": 1300, "content": "The evolution of feminist literature and its transformative impact on societal gender norms and expectations." },
  { "id": 28, "subject": "History", "type": "Article", "words": 6800, "content": "The Cold War era: Nuclear arms race, space competition, and ideological conflicts between superpowers." },
  { "id": 29, "subject": "Science", "type": "Essay", "words": 950, "content": "Human microbiome research and its revolutionary implications for understanding health and treating diseases." },
  { "id": 30, "subject": "Mathematics", "type": "Report", "words": 1600, "content": "Cryptography fundamentals: How number theory protects digital information in the internet age." },
  { "id": 31, "subject": "English", "type": "Essay", "words": 800, "content": "Postcolonial literature analysis examining cultural identity and power dynamics in formerly colonized nations." },
  { "id": 32, "subject": "Science", "type": "Report", "words": 2200, "content": "Nanotechnology breakthroughs and their potential applications in medicine, electronics, and environmental remediation." },
  { "id": 33, "subject": "History", "type": "Article", "words": 4800, "content": "The French Revolution's radical ideas and their influence on modern political systems and human rights." },
  { "id": 34, "subject": "Mathematics", "type": "Essay", "words": 700, "content": "Chaos theory explained through examples like weather systems and population dynamics in nature." },
  { "id": 35, "subject": "Science", "type": "Report", "words": 1700, "content": "Stem cell research progress and ethical considerations in regenerative medicine and therapeutic applications." },
  { "id": 36, "subject": "History", "type": "Article", "words": 5200, "content": "The Silk Road's historical significance in facilitating cultural exchange and global trade networks." },
  { "id": 37, "subject": "English", "type": "Essay", "words": 1000, "content": "Magical realism in literature: Blending fantastical elements with realistic narratives in Latin American fiction." },
  { "id": 38, "subject": "Science", "type": "Report", "words": 2400, "content": "Artificial intelligence advancements and their transformative potential across various industries and job markets." },
  { "id": 39, "subject": "Mathematics", "type": "Essay", "words": 1250, "content": "Topology concepts illustrated through everyday examples like coffee cups and doughnut transformations." },
  { "id": 40, "subject": "History", "type": "Article", "words": 7100, "content": "The Protestant Reformation's religious upheavals and their lasting effects on European society and politics." },
  { "id": 41, "subject": "English", "type": "Report", "words": 1400, "content": "The rise of graphic novels as serious literary works combining visual and textual storytelling techniques." },
  { "id": 42, "subject": "Science", "type": "Essay", "words": 900, "content": "Dark matter mysteries and ongoing scientific efforts to detect this elusive cosmic component." },
  { "id": 43, "subject": "History", "type": "Article", "words": 4900, "content": "Mesoamerican civilizations: Achievements of the Maya, Aztec, and their complex cultural developments." },
  { "id": 44, "subject": "Mathematics", "type": "Report", "words": 1800, "content": "Mathematical modeling applications in epidemiology for predicting and controlling disease outbreak patterns." },
  { "id": 45, "subject": "Science", "type": "Essay", "words": 1100, "content": "CRISPR gene editing technology and its revolutionary potential for treating genetic disorders." },
  { "id": 46, "subject": "History", "type": "Article", "words": 5300, "content": "The Age of Exploration: European voyages that reshaped global geography and cultural exchanges." },
  { "id": 47, "subject": "English", "type": "Report", "words": 1500, "content": "Digital literature evolution and how electronic media is transforming traditional narrative forms and reading." },
  { "id": 48, "subject": "Science", "type": "Essay", "words": 950, "content": "Neuroscientific discoveries about consciousness and what they reveal about human perception and cognition." },
  { "id": 49, "subject": "Mathematics", "type": "Article", "words": 2000, "content": "The history of zero: How this conceptual breakthrough revolutionized mathematics and scientific thinking globally." },
  { "id": 50, "subject": "History", "type": "Report", "words": 6500, "content": "The transatlantic slave trade's devastating consequences and its enduring legacy in contemporary societies." },
  { "id": 51, "subject": "English", "type": "Essay", "words": 850, "content": "Ecocriticism in literature: Analyzing how nature is represented and environmental themes are explored." },
  { "id": 52, "subject": "Science", "type": "Report", "words": 2300, "content": "Renewable energy storage solutions and technological innovations addressing intermittency challenges in green power." },
  { "id": 53, "subject": "History", "type": "Article", "words": 5400, "content": "The Byzantine Empire's unique position as a bridge between ancient and medieval European civilizations." },
  { "id": 54, "subject": "Mathematics", "type": "Essay", "words": 1150, "content": "Complex numbers and their surprising applications in electrical engineering and quantum physics theories." },
  { "id": 55, "subject": "Science", "type": "Report", "words": 1600, "content": "Ocean acidification research and its alarming implications for marine biodiversity and coastal ecosystems." },
  { "id": 56, "subject": "History", "type": "Article", "words": 5600, "content": "The Mongol Empire's unprecedented expansion and its effects on Eurasian trade and cultural exchange." },
  { "id": 57, "subject": "English", "type": "Essay", "words": 1050, "content": "Modernist poetry techniques and how they broke from traditional forms to express contemporary experience." },
  { "id": 58, "subject": "Science", "type": "Report", "words": 2500, "content": "Precision medicine innovations using genetic profiling to customize healthcare treatments for individuals." },
  { "id": 59, "subject": "Mathematics", "type": "Essay", "words": 1350, "content": "Graph theory applications in solving real-world network problems from social media to transportation." },
  { "id": 60, "subject": "History", "type": "Article", "words": 5800, "content": "The Scientific Revolution's paradigm shift from Aristotelian philosophy to empirical, mathematical approaches." },
  { "id": 61, "subject": "English", "type": "Report", "words": 1700, "content": "The detective fiction genre's evolution from Poe's stories to modern psychological crime thrillers." },
  { "id": 62, "subject": "Science", "type": "Essay", "words": 1000, "content": "Exoplanet discoveries and the search for habitable worlds beyond our solar system's boundaries." },
  { "id": 63, "subject": "History", "type": "Article", "words": 5900, "content": "The Enlightenment's intellectual movement and its profound influence on modern democratic ideals and science." },
  { "id": 64, "subject": "Mathematics", "type": "Report", "words": 1900, "content": "Fluid dynamics mathematics modeling weather patterns, aircraft design, and blood flow in arteries." },
  { "id": 65, "subject": "Science", "type": "Essay", "words": 1200, "content": "Antibiotic resistance crisis and the urgent need for novel antimicrobial drug development strategies." },
  { "id": 66, "subject": "History", "type": "Article", "words": 6000, "content": "The Crusades' complex religious wars and their lasting impacts on Christian-Muslim relations historically." },
  { "id": 67, "subject": "English", "type": "Report", "words": 1800, "content": "The graphic memoir's emergence as powerful autobiographical storytelling combining words and visual elements." },
  { "id": 68, "subject": "Science", "type": "Essay", "words": 1300, "content": "Black hole physics and recent astronomical observations confirming Einstein's general relativity predictions." },
  { "id": 69, "subject": "Mathematics", "type": "Article", "words": 2100, "content": "Number theory's unexpected applications in modern computer security systems and encryption protocols." },
  { "id": 70, "subject": "History", "type": "Report", "words": 6200, "content": "The Haitian Revolution's significance as the only successful slave revolt creating an independent nation." },
  { "id": 71, "subject": "English", "type": "Essay", "words": 950, "content": "Postmodern literature characteristics: Fragmentation, paradox, and unreliable narration in contemporary fiction." },
  { "id": 72, "subject": "Science", "type": "Report", "words": 2600, "content": "Synthetic biology advancements and the engineering of biological systems for industrial applications." },
  { "id": 73, "subject": "History", "type": "Article", "words": 6300, "content": "The Meiji Restoration's rapid modernization of Japan and its emergence as a world power." },
  { "id": 74, "subject": "Mathematics", "type": "Essay", "words": 1450, "content": "The mathematics of music: Exploring harmonics, frequency ratios, and mathematical patterns in composition." },
  { "id": 75, "subject": "Science", "type": "Report", "words": 1700, "content": "Vertical farming technologies and their potential to revolutionize urban agriculture sustainability." },
  { "id": 76, "subject": "History", "type": "Article", "words": 6400, "content": "The African diaspora's cultural impacts through forced migration and voluntary global movements." },
  { "id": 77, "subject": "English", "type": "Essay", "words": 1100, "content": "Transgressive fiction analysis: How controversial literature challenges societal norms and moral boundaries." },
  { "id": 78, "subject": "Science", "type": "Report", "words": 2700, "content": "Quantum computing developments and their potential to solve currently intractable computational problems." },
  { "id": 79, "subject": "Mathematics", "type": "Article", "words": 2200, "content": "Non-Euclidean geometries and their revolutionary impact on mathematics and Einstein's physics theories." },
  { "id": 80, "subject": "History", "type": "Report", "words": 6600, "content": "The Vietnam War's divisive effects on American society and its complicated geopolitical legacy." },
  { "id": 81, "subject": "English", "type": "Essay", "words": 1200, "content": "The rise of autofiction: Blurring boundaries between autobiography and novelistic imagination in literature." },
  { "id": 82, "subject": "Science", "type": "Report", "words": 2800, "content": "Tissue engineering breakthroughs creating artificial organs and advancing regenerative medicine possibilities." },
  { "id": 83, "subject": "History", "type": "Article", "words": 6700, "content": "The Russian Revolution's radical transformation of society and its global ideological consequences." },
  { "id": 84, "subject": "Mathematics", "type": "Essay", "words": 1550, "content": "Optimization mathematics applied to business logistics, supply chain management, and operations research." },
  { "id": 85, "subject": "Science", "type": "Report", "words": 1800, "content": "Paleogenomics: Reconstructing ancient DNA to understand human evolution and prehistoric population movements." },
  { "id": 86, "subject": "History", "type": "Article", "words": 6800, "content": "The Bronze Age collapse: Analyzing possible causes of this ancient civilization-ending catastrophe." },
  { "id": 87, "subject": "English", "type": "Essay", "words": 1300, "content": "Speculative fiction's role in exploring alternative social structures and possible future scenarios." },
  { "id": 88, "subject": "Science", "type": "Report", "words": 2900, "content": "Biomimicry in engineering: How nature-inspired designs are solving complex human technological challenges." },
  { "id": 89, "subject": "Mathematics", "type": "Article", "words": 2300, "content": "Category theory's unifying framework across different branches of advanced mathematics and physics." },
  { "id": 90, "subject": "History", "type": "Report", "words": 6900, "content": "The Atlantic Revolutions: Comparative analysis of American, French, and Haitian revolutionary movements." },
  { "id": 91, "subject": "English", "type": "Essay", "words": 1400, "content": "Experimental literature techniques pushing boundaries of narrative form and reader expectations." },
  { "id": 92, "subject": "Science", "type": "Report", "words": 3000, "content": "Astrobiology research investigating the potential for life in extreme environments throughout the universe." },
  { "id": 93, "subject": "History", "type": "Article", "words": 7000, "content": "The Columbian Exchange's biological and cultural impacts following European contact with the Americas." },
  { "id": 94, "subject": "Mathematics", "type": "Essay", "words": 1650, "content": "Financial mathematics models used in risk assessment and derivative pricing in global markets." },
  { "id": 95, "subject": "Science", "type": "Report", "words": 1900, "content": "Metamaterials research creating substances with properties not found in naturally occurring materials." },
  { "id": 96, "subject": "History", "type": "Article", "words": 7100, "content": "The women's suffrage movement's global struggle for voting rights and gender equality." },
  { "id": 97, "subject": "English", "type": "Essay", "words": 1500, "content": "The unreliable narrator device and its effects on reader interpretation in complex novels." },
  { "id": 98, "subject": "Science", "type": "Report", "words": 3100, "content": "Neural interface technologies bridging brains with computers for medical and enhancement applications." },
  { "id": 99, "subject": "Mathematics", "type": "Article", "words": 2400, "content": "Computational complexity theory classifying problems by their inherent difficulty and resource requirements." },
  { "id": 100, "subject": "History", "type": "Report", "words": 7200, "content": "Decolonization movements in the 20th century and their reshaping of the global political order." }
]