import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";
export const metadata: Metadata = {
  title: "Expert Buddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      
      <body >
      
        {children}
      </body>
    </html>
  );
}
