import type { Metadata } from "next";
import NavBar from "@/components/NavBar";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Manrope } from "next/font/google";
export const metadata: Metadata = {
  title: "Expert Buddy",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Add weights as needed
  variable: "--font-manrope", // Set a CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      
      <body >
      
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
